// data.js — the vocabulary. Nine everyday categories, each holding
// simple, high-frequency words and phrases picked for real use (a
// market stall, a taxi, a first conversation) rather than textbook
// completeness. Every word carries a short example sentence so a
// flashcard is never just a bare translation.

export const CATEGORIES = [
  {
    id: 'greetings',
    name: 'Greetings & Manners',
    native: 'Salam & Sopan Santun',
    blurb: 'The words that open and close every conversation.',
    words: [
      { id: 'greet-hello', indo: 'Halo', en: 'Hello', example: 'Halo, apa kabar?', exampleEn: 'Hello, how are you?' },
      { id: 'greet-morning', indo: 'Selamat pagi', en: 'Good morning', example: 'Selamat pagi, Pak.', exampleEn: 'Good morning, sir.' },
      { id: 'greet-afternoon', indo: 'Selamat siang', en: 'Good afternoon', example: 'Selamat siang, Bu.', exampleEn: 'Good afternoon, ma’am.' },
      { id: 'greet-evening', indo: 'Selamat sore', en: 'Good evening', example: 'Selamat sore, semuanya.', exampleEn: 'Good evening, everyone.' },
      { id: 'greet-night', indo: 'Selamat malam', en: 'Good night', example: 'Selamat malam, sampai besok.', exampleEn: 'Good night, see you tomorrow.' },
      { id: 'greet-howareyou', indo: 'Apa kabar?', en: 'How are you?', example: 'Halo! Apa kabar hari ini?', exampleEn: 'Hi! How are you today?' },
      { id: 'greet-imfine', indo: 'Baik-baik saja', en: 'I’m fine', example: 'Saya baik-baik saja, terima kasih.', exampleEn: 'I’m fine, thank you.' },
      { id: 'greet-thanks', indo: 'Terima kasih', en: 'Thank you', example: 'Terima kasih atas bantuannya.', exampleEn: 'Thank you for your help.' },
      { id: 'greet-welcome', indo: 'Sama-sama', en: 'You’re welcome', example: 'Sama-sama, senang bisa membantu.', exampleEn: 'You’re welcome, happy to help.' },
      { id: 'greet-excuseme', indo: 'Permisi', en: 'Excuse me', example: 'Permisi, boleh saya lewat?', exampleEn: 'Excuse me, may I pass?' },
      { id: 'greet-sorry', indo: 'Maaf', en: 'Sorry', example: 'Maaf, saya terlambat.', exampleEn: 'Sorry, I’m late.' },
      { id: 'greet-please-help', indo: 'Tolong', en: 'Please (asking for help)', example: 'Tolong bantu saya.', exampleEn: 'Please help me.' },
      { id: 'greet-please-offer', indo: 'Silakan', en: 'Please (go ahead)', example: 'Silakan duduk.', exampleEn: 'Please, sit down.' },
      { id: 'greet-seeyou', indo: 'Sampai jumpa', en: 'See you later', example: 'Sampai jumpa besok pagi.', exampleEn: 'See you tomorrow morning.' },
      { id: 'greet-goodbye', indo: 'Selamat tinggal', en: 'Goodbye', example: 'Selamat tinggal, jaga diri baik-baik.', exampleEn: 'Goodbye, take good care.' },
    ],
  },
  {
    id: 'numbers',
    name: 'Numbers',
    native: 'Angka',
    blurb: 'Counting, prices, and how much things cost.',
    words: [
      { id: 'num-one', indo: 'Satu', en: 'One', example: 'Saya mau satu tiket.', exampleEn: 'I’d like one ticket.' },
      { id: 'num-two', indo: 'Dua', en: 'Two', example: 'Tolong dua kopi.', exampleEn: 'Two coffees, please.' },
      { id: 'num-three', indo: 'Tiga', en: 'Three', example: 'Ada tiga kursi kosong.', exampleEn: 'There are three empty seats.' },
      { id: 'num-four', indo: 'Empat', en: 'Four', example: 'Kami berempat.', exampleEn: 'There are four of us.' },
      { id: 'num-five', indo: 'Lima', en: 'Five', example: 'Lima menit lagi.', exampleEn: 'Five more minutes.' },
      { id: 'num-six', indo: 'Enam', en: 'Six', example: 'Toko buka jam enam.', exampleEn: 'The shop opens at six.' },
      { id: 'num-seven', indo: 'Tujuh', en: 'Seven', example: 'Tujuh hari dalam seminggu.', exampleEn: 'Seven days in a week.' },
      { id: 'num-eight', indo: 'Delapan', en: 'Eight', example: 'Jam delapan malam.', exampleEn: 'At eight in the evening.' },
      { id: 'num-nine', indo: 'Sembilan', en: 'Nine', example: 'Kamar nomor sembilan.', exampleEn: 'Room number nine.' },
      { id: 'num-ten', indo: 'Sepuluh', en: 'Ten', example: 'Sepuluh ribu rupiah.', exampleEn: 'Ten thousand rupiah.' },
      { id: 'num-hundred', indo: 'Seratus', en: 'One hundred', example: 'Harganya seratus ribu.', exampleEn: 'It costs one hundred thousand.' },
      { id: 'num-thousand', indo: 'Seribu', en: 'One thousand', example: 'Cukup seribu saja.', exampleEn: 'Just one thousand is enough.' },
      { id: 'num-howmuch', indo: 'Berapa?', en: 'How much / how many?', example: 'Ini berapa harganya?', exampleEn: 'How much is this?' },
      { id: 'num-cheap', indo: 'Murah', en: 'Cheap', example: 'Harganya sangat murah.', exampleEn: 'The price is very cheap.' },
      { id: 'num-expensive', indo: 'Mahal', en: 'Expensive', example: 'Menurut saya ini mahal.', exampleEn: 'I think this is expensive.' },
    ],
  },
  {
    id: 'family',
    name: 'Family & People',
    native: 'Keluarga',
    blurb: 'Talking about who’s who.',
    words: [
      { id: 'fam-family', indo: 'Keluarga', en: 'Family', example: 'Ini keluarga saya.', exampleEn: 'This is my family.' },
      { id: 'fam-father', indo: 'Ayah', en: 'Father', example: 'Ayah saya seorang guru.', exampleEn: 'My father is a teacher.' },
      { id: 'fam-mother', indo: 'Ibu', en: 'Mother', example: 'Ibu sedang memasak.', exampleEn: 'Mother is cooking.' },
      { id: 'fam-child', indo: 'Anak', en: 'Child', example: 'Kami punya dua anak.', exampleEn: 'We have two children.' },
      { id: 'fam-husband', indo: 'Suami', en: 'Husband', example: 'Suami saya bekerja di bank.', exampleEn: 'My husband works at a bank.' },
      { id: 'fam-wife', indo: 'Istri', en: 'Wife', example: 'Istri saya suka membaca.', exampleEn: 'My wife likes reading.' },
      { id: 'fam-olderSibling', indo: 'Kakak', en: 'Older sibling', example: 'Kakak saya tinggal di Jakarta.', exampleEn: 'My older sibling lives in Jakarta.' },
      { id: 'fam-youngerSibling', indo: 'Adik', en: 'Younger sibling', example: 'Adik saya masih sekolah.', exampleEn: 'My younger sibling is still in school.' },
      { id: 'fam-grandmother', indo: 'Nenek', en: 'Grandmother', example: 'Nenek tinggal di desa.', exampleEn: 'Grandmother lives in the village.' },
      { id: 'fam-grandfather', indo: 'Kakek', en: 'Grandfather', example: 'Kakek suka berkebun.', exampleEn: 'Grandfather likes gardening.' },
      { id: 'fam-friend', indo: 'Teman', en: 'Friend', example: 'Dia teman baik saya.', exampleEn: 'He’s a good friend of mine.' },
      { id: 'fam-son', indo: 'Anak laki-laki', en: 'Son', example: 'Anak laki-lakinya sudah besar.', exampleEn: 'His son is already grown up.' },
      { id: 'fam-daughter', indo: 'Anak perempuan', en: 'Daughter', example: 'Anak perempuannya masih kecil.', exampleEn: 'Her daughter is still young.' },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    native: 'Makanan & Minuman',
    blurb: 'Ordering, describing taste, and everyday eating.',
    words: [
      { id: 'food-eat', indo: 'Makan', en: 'To eat', example: 'Ayo kita makan.', exampleEn: 'Let’s eat.' },
      { id: 'food-drink', indo: 'Minum', en: 'To drink', example: 'Saya mau minum air.', exampleEn: 'I’d like to drink water.' },
      { id: 'food-water', indo: 'Air', en: 'Water', example: 'Tolong satu gelas air.', exampleEn: 'One glass of water, please.' },
      { id: 'food-rice', indo: 'Nasi', en: 'Rice', example: 'Saya suka nasi goreng.', exampleEn: 'I like fried rice.' },
      { id: 'food-chicken', indo: 'Ayam', en: 'Chicken', example: 'Ayam bakar ini enak sekali.', exampleEn: 'This grilled chicken is delicious.' },
      { id: 'food-delicious', indo: 'Enak', en: 'Delicious', example: 'Masakannya sangat enak.', exampleEn: 'The food is very delicious.' },
      { id: 'food-spicy', indo: 'Pedas', en: 'Spicy', example: 'Hati-hati, ini pedas.', exampleEn: 'Careful, this is spicy.' },
      { id: 'food-sweet', indo: 'Manis', en: 'Sweet', example: 'Saya suka teh manis.', exampleEn: 'I like sweet tea.' },
      { id: 'food-coffee', indo: 'Kopi', en: 'Coffee', example: 'Satu kopi hitam, tolong.', exampleEn: 'One black coffee, please.' },
      { id: 'food-tea', indo: 'Teh', en: 'Tea', example: 'Boleh minta teh hangat?', exampleEn: 'May I have warm tea?' },
      { id: 'food-hungry', indo: 'Lapar', en: 'Hungry', example: 'Saya sudah lapar.', exampleEn: 'I’m already hungry.' },
      { id: 'food-thirsty', indo: 'Haus', en: 'Thirsty', example: 'Anak itu terlihat haus.', exampleEn: 'That child looks thirsty.' },
      { id: 'food-full', indo: 'Sudah kenyang', en: 'Already full', example: 'Terima kasih, saya sudah kenyang.', exampleEn: 'Thank you, I’m already full.' },
      { id: 'food-menu', indo: 'Boleh minta menu?', en: 'May I have the menu?', example: 'Permisi, boleh minta menu?', exampleEn: 'Excuse me, may I have the menu?' },
      { id: 'food-verydelicious', indo: 'Enak sekali!', en: 'Very delicious!', example: 'Wah, enak sekali masakan ini!', exampleEn: 'Wow, this dish is very delicious!' },
    ],
  },
  {
    id: 'shopping',
    name: 'Shopping & Money',
    native: 'Belanja & Uang',
    blurb: 'The market, the mall, and getting a fair price.',
    words: [
      { id: 'shop-howmuch', indo: 'Berapa harganya?', en: 'How much does it cost?', example: 'Permisi, berapa harganya?', exampleEn: 'Excuse me, how much does this cost?' },
      { id: 'shop-expensive', indo: 'Mahal', en: 'Expensive', example: 'Ini agak mahal untuk saya.', exampleEn: 'This is a bit expensive for me.' },
      { id: 'shop-cheap', indo: 'Murah', en: 'Cheap', example: 'Di sini lebih murah.', exampleEn: 'It’s cheaper here.' },
      { id: 'shop-money', indo: 'Uang', en: 'Money', example: 'Saya tidak bawa banyak uang.', exampleEn: 'I don’t have much money with me.' },
      { id: 'shop-buy', indo: 'Beli', en: 'To buy', example: 'Saya mau beli ini.', exampleEn: 'I want to buy this.' },
      { id: 'shop-sell', indo: 'Jual', en: 'To sell', example: 'Toko ini jual oleh-oleh.', exampleEn: 'This shop sells souvenirs.' },
      { id: 'shop-lesser', indo: 'Bisa kurang?', en: 'Can it be less?', example: 'Bisa kurang sedikit, Bu?', exampleEn: 'Can it be a bit less, ma’am?' },
      { id: 'shop-discount', indo: 'Ada diskon?', en: 'Is there a discount?', example: 'Ada diskon untuk ini?', exampleEn: 'Is there a discount on this?' },
      { id: 'shop-size', indo: 'Ukuran', en: 'Size', example: 'Ada ukuran yang lebih besar?', exampleEn: 'Is there a bigger size?' },
      { id: 'shop-color', indo: 'Warna', en: 'Color', example: 'Saya suka warna biru.', exampleEn: 'I like the blue color.' },
      { id: 'shop-creditcard', indo: 'Kartu kredit', en: 'Credit card', example: 'Bisa bayar pakai kartu kredit?', exampleEn: 'Can I pay with a credit card?' },
      { id: 'shop-cash', indo: 'Tunai', en: 'Cash', example: 'Saya bayar tunai saja.', exampleEn: 'I’ll just pay cash.' },
      { id: 'shop-change', indo: 'Kembalian', en: 'Change (money)', example: 'Ini kembaliannya, Pak.', exampleEn: 'Here’s your change, sir.' },
    ],
  },
  {
    id: 'directions',
    name: 'Directions & Transport',
    native: 'Arah & Transportasi',
    blurb: 'Getting where you’re going, and asking when lost.',
    words: [
      { id: 'dir-where', indo: 'Di mana?', en: 'Where?', example: 'Stasiun di mana, ya?', exampleEn: 'Where is the station?' },
      { id: 'dir-left', indo: 'Kiri', en: 'Left', example: 'Belok kiri di sana.', exampleEn: 'Turn left over there.' },
      { id: 'dir-right', indo: 'Kanan', en: 'Right', example: 'Belok kanan setelah lampu merah.', exampleEn: 'Turn right after the traffic light.' },
      { id: 'dir-straight', indo: 'Lurus', en: 'Straight', example: 'Jalan terus lurus saja.', exampleEn: 'Just keep going straight.' },
      { id: 'dir-near', indo: 'Dekat', en: 'Near', example: 'Hotelnya dekat dari sini.', exampleEn: 'The hotel is near from here.' },
      { id: 'dir-far', indo: 'Jauh', en: 'Far', example: 'Apakah pasar itu jauh?', exampleEn: 'Is that market far?' },
      { id: 'dir-station', indo: 'Stasiun', en: 'Station', example: 'Kita turun di stasiun berikutnya.', exampleEn: 'We get off at the next station.' },
      { id: 'dir-airport', indo: 'Bandara', en: 'Airport', example: 'Berapa lama ke bandara?', exampleEn: 'How long to the airport?' },
      { id: 'dir-street', indo: 'Jalan', en: 'Street', example: 'Rumahnya di jalan ini.', exampleEn: 'The house is on this street.' },
      { id: 'dir-taxi', indo: 'Taksi', en: 'Taxi', example: 'Tolong panggilkan taksi.', exampleEn: 'Please call a taxi.' },
      { id: 'dir-stophere', indo: 'Berhenti di sini', en: 'Stop here', example: 'Pak, berhenti di sini saja.', exampleEn: 'Sir, just stop here.' },
      { id: 'dir-toilet', indo: 'Toilet di mana?', en: 'Where’s the toilet?', example: 'Permisi, toilet di mana?', exampleEn: 'Excuse me, where’s the toilet?' },
    ],
  },
  {
    id: 'time',
    name: 'Time & Days',
    native: 'Waktu & Hari',
    blurb: 'When things happen, and the days of the week.',
    words: [
      { id: 'time-now', indo: 'Sekarang', en: 'Now', example: 'Kita berangkat sekarang.', exampleEn: 'We’re leaving now.' },
      { id: 'time-later', indo: 'Nanti', en: 'Later', example: 'Saya telepon nanti sore.', exampleEn: 'I’ll call later this evening.' },
      { id: 'time-today', indo: 'Hari ini', en: 'Today', example: 'Hari ini cuacanya panas.', exampleEn: 'Today the weather is hot.' },
      { id: 'time-tomorrow', indo: 'Besok', en: 'Tomorrow', example: 'Sampai jumpa besok.', exampleEn: 'See you tomorrow.' },
      { id: 'time-yesterday', indo: 'Kemarin', en: 'Yesterday', example: 'Kemarin saya sangat sibuk.', exampleEn: 'I was very busy yesterday.' },
      { id: 'time-whattime', indo: 'Jam berapa?', en: 'What time is it?', example: 'Maaf, sekarang jam berapa?', exampleEn: 'Excuse me, what time is it now?' },
      { id: 'time-monday', indo: 'Senin', en: 'Monday', example: 'Toko tutup hari Senin.', exampleEn: 'The shop is closed on Monday.' },
      { id: 'time-tuesday', indo: 'Selasa', en: 'Tuesday', example: 'Kita bertemu hari Selasa.', exampleEn: 'We’re meeting on Tuesday.' },
      { id: 'time-wednesday', indo: 'Rabu', en: 'Wednesday', example: 'Rabu depan ada rapat.', exampleEn: 'There’s a meeting next Wednesday.' },
      { id: 'time-thursday', indo: 'Kamis', en: 'Thursday', example: 'Penerbangan saya hari Kamis.', exampleEn: 'My flight is on Thursday.' },
      { id: 'time-friday', indo: 'Jumat', en: 'Friday', example: 'Akhirnya, hari Jumat!', exampleEn: 'Finally, it’s Friday!' },
      { id: 'time-saturday', indo: 'Sabtu', en: 'Saturday', example: 'Kami pergi ke pasar hari Sabtu.', exampleEn: 'We go to the market on Saturday.' },
      { id: 'time-sunday', indo: 'Minggu', en: 'Sunday', example: 'Hari Minggu kami istirahat.', exampleEn: 'On Sunday we rest.' },
    ],
  },
  {
    id: 'health',
    name: 'Health & Emergencies',
    native: 'Kesehatan & Darurat',
    blurb: 'Words worth knowing before you ever need them.',
    words: [
      { id: 'health-help', indo: 'Tolong!', en: 'Help!', example: 'Tolong! Ada kecelakaan!', exampleEn: 'Help! There’s an accident!' },
      { id: 'health-sick', indo: 'Sakit', en: 'Sick / pain', example: 'Kepala saya sakit.', exampleEn: 'My head hurts.' },
      { id: 'health-doctor', indo: 'Dokter', en: 'Doctor', example: 'Saya perlu bertemu dokter.', exampleEn: 'I need to see a doctor.' },
      { id: 'health-hospital', indo: 'Rumah sakit', en: 'Hospital', example: 'Rumah sakit terdekat di mana?', exampleEn: 'Where’s the nearest hospital?' },
      { id: 'health-pharmacy', indo: 'Apotek', en: 'Pharmacy', example: 'Apotek buka sampai jam berapa?', exampleEn: 'Until what time is the pharmacy open?' },
      { id: 'health-needhelp', indo: 'Saya butuh bantuan', en: 'I need help', example: 'Maaf, saya butuh bantuan.', exampleEn: 'Sorry, I need help.' },
      { id: 'health-police', indo: 'Polisi', en: 'Police', example: 'Tolong hubungi polisi.', exampleEn: 'Please call the police.' },
      { id: 'health-careful', indo: 'Hati-hati', en: 'Be careful', example: 'Hati-hati, jalannya licin.', exampleEn: 'Be careful, the road is slippery.' },
      { id: 'health-ambulance', indo: 'Panggil ambulans', en: 'Call an ambulance', example: 'Cepat, panggil ambulans!', exampleEn: 'Quick, call an ambulance!' },
      { id: 'health-allergic', indo: 'Saya alergi', en: 'I am allergic', example: 'Saya alergi kacang.', exampleEn: 'I am allergic to peanuts.' },
    ],
  },
  {
    id: 'smalltalk',
    name: 'Small Talk',
    native: 'Obrolan Ringan',
    blurb: 'Introducing yourself and keeping a conversation going.',
    words: [
      { id: 'talk-myname', indo: 'Nama saya...', en: 'My name is...', example: 'Nama saya Sarah.', exampleEn: 'My name is Sarah.' },
      { id: 'talk-yourname', indo: 'Siapa nama Anda?', en: 'What’s your name?', example: 'Halo, siapa nama Anda?', exampleEn: 'Hi, what’s your name?' },
      { id: 'talk-wherefrom', indo: 'Dari mana?', en: 'Where are you from?', example: 'Anda dari mana?', exampleEn: 'Where are you from?' },
      { id: 'talk-imfrom', indo: 'Saya dari...', en: 'I am from...', example: 'Saya dari Singapura.', exampleEn: 'I am from Singapore.' },
      { id: 'talk-speakenglish', indo: 'Anda bisa bahasa Inggris?', en: 'Do you speak English?', example: 'Maaf, Anda bisa bahasa Inggris?', exampleEn: 'Sorry, do you speak English?' },
      { id: 'talk-dontunderstand', indo: 'Saya tidak mengerti', en: 'I don’t understand', example: 'Maaf, saya tidak mengerti.', exampleEn: 'Sorry, I don’t understand.' },
      { id: 'talk-repeat', indo: 'Bisa tolong ulangi?', en: 'Can you repeat, please?', example: 'Bisa tolong ulangi lagi?', exampleEn: 'Can you please say that again?' },
      { id: 'talk-good', indo: 'Bagus', en: 'Good / nice', example: 'Idenya bagus sekali.', exampleEn: 'That’s a really good idea.' },
      { id: 'talk-yes', indo: 'Ya', en: 'Yes', example: 'Ya, betul sekali.', exampleEn: 'Yes, that’s exactly right.' },
      { id: 'talk-no', indo: 'Tidak', en: 'No', example: 'Tidak, terima kasih.', exampleEn: 'No, thank you.' },
      { id: 'talk-maybe', indo: 'Mungkin', en: 'Maybe', example: 'Mungkin besok saya bisa datang.', exampleEn: 'Maybe I can come tomorrow.' },
    ],
  },
];

export const ALL_WORDS = CATEGORIES.flatMap((cat) => cat.words.map((w) => ({ ...w, categoryId: cat.id })));

export function getCategory(categoryId) {
  return CATEGORIES.find((c) => c.id === categoryId);
}

export function findWord(wordId) {
  return ALL_WORDS.find((w) => w.id === wordId);
}
